import type { BriefingItem, GroupedDigest } from "./types.js";

const BL_LABEL: Record<string, string> = {
  prosumer: "Prosumer (PLG)",
  b2b: "B2B (Sales-led)",
  shared: "Shared / Cross-team",
};

const FN_EMOJI: Record<string, string> = {
  product: ":hammer_and_wrench:",
  sales: ":moneybag:",
  support: ":sos:",
  ops: ":gear:",
  eng: ":construction:",
  marketing: ":mega:",
  leadership: ":crown:",
};

function fmtItem(it: BriefingItem): string {
  const owner = it.owner ? ` _(${it.owner})_` : "";
  if (it.permalink) {
    return `• <${it.permalink}|${it.channel}> — ${it.text}${owner}`;
  }
  return `• ${it.channel} — ${it.text}${owner}`;
}

function section(title: string, items: BriefingItem[]): string | null {
  if (!items || items.length === 0) return null;
  return `*${title}*\n${items.map(fmtItem).join("\n")}`;
}

export function composeBriefing(
  digests: GroupedDigest[],
  windowHours: number,
  isMonday: boolean,
): { blocks: any[]; fallbackText: string } {
  const blocks: any[] = [];

  const dateStr = new Date().toLocaleDateString("en-IN", {
    weekday: "long",
    day: "numeric",
    month: "short",
    timeZone: "Asia/Kolkata",
  });

  blocks.push({
    type: "header",
    text: { type: "plain_text", text: `:sunrise: Standup Brief — ${dateStr}` },
  });
  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: `Last *${windowHours}h* across ${digests.reduce(
          (s, d) => s + d.channels.length,
          0,
        )} channels${isMonday ? " · Monday catch-up window" : ""}`,
      },
    ],
  });

  // Top-of-brief alarms: pull customer issues + blockers from ALL groups so they're impossible to miss.
  const topIssues = digests.flatMap((d) =>
    d.digest.customer_issues.map((i) => ({ ...i, _bl: d.group.business_line })),
  );
  const topBlockers = digests.flatMap((d) => d.digest.blockers);

  if (topIssues.length > 0) {
    blocks.push({ type: "divider" });
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `:rotating_light: *Customer issues & incidents (${topIssues.length})*\n${topIssues
          .slice(0, 12)
          .map(fmtItem)
          .join("\n")}`,
      },
    });
  }

  if (topBlockers.length > 0) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `:no_entry: *Blockers (${topBlockers.length})*\n${topBlockers
          .slice(0, 10)
          .map(fmtItem)
          .join("\n")}`,
      },
    });
  }

  // Group sections — sorted: prosumer first, b2b next, shared last.
  const order: Record<string, number> = { prosumer: 0, b2b: 1, shared: 2 };
  const sorted = [...digests].sort(
    (a, b) =>
      (order[a.group.business_line] ?? 9) - (order[b.group.business_line] ?? 9),
  );

  // Group by business_line, then by function within.
  const byBL = new Map<string, GroupedDigest[]>();
  for (const d of sorted) {
    const key = d.group.business_line;
    if (!byBL.has(key)) byBL.set(key, []);
    byBL.get(key)!.push(d);
  }

  for (const [bl, groups] of byBL) {
    blocks.push({ type: "divider" });
    blocks.push({
      type: "header",
      text: { type: "plain_text", text: BL_LABEL[bl] ?? bl },
    });

    for (const g of groups) {
      if (g.message_count === 0) continue;
      const emoji = FN_EMOJI[g.group.function] ?? ":small_blue_diamond:";
      const parts: string[] = [];
      parts.push(
        `${emoji} *${g.group.function.toUpperCase()}* — ${g.message_count} msgs across ${g.channels
          .map((c) => `#${c}`)
          .join(", ")}`,
      );

      if (g.digest.themes.length > 0) {
        parts.push(`_${g.digest.themes.map((t) => `• ${t}`).join("\n")}_`);
      }

      const s1 = section(
        "Open action items / follow-ups",
        g.digest.open_action_items,
      );
      const s2 = section("Decisions", g.digest.decisions);
      // Customer issues + blockers already shown at the top, but include
      // again per-group so context isn't lost.
      const s3 = section("Customer issues", g.digest.customer_issues);
      const s4 = section("Blockers", g.digest.blockers);

      [s1, s2, s3, s4].filter(Boolean).forEach((s) => parts.push(s as string));

      // Slack section text limit is 3000 chars; chunk if needed.
      const full = parts.join("\n\n");
      for (const chunk of chunk3000(full)) {
        blocks.push({ type: "section", text: { type: "mrkdwn", text: chunk } });
      }
    }
  }

  blocks.push({ type: "divider" });
  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: ":robot_face: Auto-generated by superjoin-standup-bot · React with :white_check_mark: to mark items handled · `/standup-brief` to regenerate",
      },
    ],
  });

  const fallbackText = `Standup brief — ${dateStr}: ${topIssues.length} customer issues, ${topBlockers.length} blockers across ${digests.length} groups.`;
  return { blocks, fallbackText };
}

function chunk3000(s: string): string[] {
  if (s.length <= 2900) return [s];
  const out: string[] = [];
  let buf = "";
  for (const line of s.split("\n")) {
    if (buf.length + line.length + 1 > 2900) {
      out.push(buf);
      buf = "";
    }
    buf += (buf ? "\n" : "") + line;
  }
  if (buf) out.push(buf);
  return out;
}
